# Dados de conexão do seu Neon (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-cold-silence-aq52makl-pooler.c-8.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=gerson
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate (Mantenha assim para criar as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect