# Dados de conexão do seu Neon (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-cold-silence-aq52makl-pooler.c-8.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&preferQueryMode=simple&scramIterations=4096
spring.datasource.username=gerson
spring.datasource.password=npg_fvdSaM21tzjT
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate (Mantenha assim para criar as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE